site_name: Achewood on Material for MkDocs
site_url: https://josh-wong.github.io/achewood/

# Add repository details in the top right-hand corner
repo_name: josh-wong/achewood
repo_url: https://github.com/josh-wong/achewood
# > **Warning**
# >
# > This edit page button does not work. I have prioritized the 
# multidocs site, so the edit page button on https://josh-wong.github.io 
# is correct; there doesn't seem to be a way to remove it from one site 
# and keep it on the other.
# edit_uri: blob/main/

plugins:
  - search
  # Show the last updated date
  #- git-revision-date-localized:
      #type: date
  # Enable videos to be embedded
  #- mkdocs-video:
  #    css_style:
  #      width: "100%"
  #      height: "300px"
  # Enable support for social cards (pretty link previews)
  - social
  #- techdocs-core

markdown_extensions:
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add support for Material for MkDocs admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: material
  # Add favicon to browser tab
  favicon: https://www.achewood.com/favicon.ico
  # Add logos to docs page
  logo: https://www.achewood.com/favicon.ico
  # Add icon to show repository information and link
  icon:
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  # Add light & dark theme
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: light green
      accent: blue
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: light green
      accent: blue
  features:
    # Add custom search functions
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    # Remove "Back to top" button since each page is already short.
    #- navigation.top
    # Auto-expand each nav section
    #- navigation.expand

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

#nav:
#  - Overview: 'index.md'
#  - '': ''
#  - '': ''
#  - 🏠Home: 'https://josh-wong.github.io'
